#!/bin/sh
# Renders the fonts of the LVGL interface into src/fonts, see tools/fonts/README.md.
#
#   tools/mkfonts.sh
#
# Needs Node.js for npx lv_font_conv on the host, not in the image.
set -e
cd "$(dirname "$0")/.."

# DejaVu Sans: ASCII, Latin-1, Latin Extended-A, modern Greek and Cyrillic, Arabic and Persian with the forms LVGL joins, typographic punctuation, arrows and a few symbols
# (U+2328 keyboard for remote support, check, cross, warning, play).
TEXT="0x20-0x7E,0xA0-0x17F,0x384-0x38A,0x38C,0x38E-0x3A1,0x3A3-0x3CE,0x400-0x45F,0x490-0x491,0x60C,0x61B,0x61F,0x621-0x652,0x660-0x669,0x67E,0x686,0x698,0x6A9,0x6AF,0x6CC,0xFB56-0xFB59,0xFB7A-0xFB7D,0xFB8A-0xFB8B,0xFB8E-0xFB95,0xFBFC-0xFBFF,0xFE70-0xFEFC,0x2013-0x2014,0x2018-0x201A,0x201C-0x201E,0x2022,0x2026,0x2190-0x2193,0x2328,0x2713,0x2717,0x26A0,0x25B6"
# Font Awesome icons of the menu: rotate-right, file-lines, paper-plane, puzzle-piece, cloud-arrow-down,
# sliders, life-ring, microchip, layer-group, headset, circle-info, right-from-bracket.
ICONS="0xF2F9,0xF15C,0xF1D8,0xF12E,0xF0ED,0xF1DE,0xF1CD,0xF2DB,0xF5FD,0xF590,0xF05A,0xF2F5"

mkdir -p src/fonts
for size in 14 16 18 20 24 28 32; do
	npx -y lv_font_conv --bpp 4 --size "$size" --format lvgl \
		--font tools/fonts/DejaVuSans.ttf -r "$TEXT" \
		--font tools/fonts/fontawesome/fa-solid-900.ttf -r "$ICONS" \
		--lv-include lvgl.h --lv-font-name "orm_font_$size" -o "src/fonts/orm_font_$size.c.tmp"
	{
		echo "/* Generated by tools/mkfonts.sh, do not edit. Rendered from DejaVu Sans 2.37"
		echo " * (Bitstream Vera and Arev licenses, tools/fonts/DejaVuSans-LICENSE.txt) and icons of"
		echo " * Font Awesome 7.3.1 Free Solid (SIL OFL 1.1, tools/fonts/fontawesome/LICENSE.txt). */"
		sed -e :a -e '/^\n*$/{$d;N;ba' -e '}' "src/fonts/orm_font_$size.c.tmp"  # Without the empty lines at the end.
	} > "src/fonts/orm_font_$size.c"
	rm "src/fonts/orm_font_$size.c.tmp"
done
